Repository jhnc-oss/yocto-build, pull requests merged in 2021-11, with the labels that each got.

#22 Switch to upstream to https
  .github/workflows/ci.yml
Labels: bug

#24 Set image version explicitly
  .github/workflows/ci.yml
Labels: ci, enhancement

#26 Fix arch propagation on CI builds
  .github/workflows/ci.yml
Labels: bug, ci
