Repository jhnc-oss/yocto-build, pull requests merged in 2021-07, with the labels that each got.

#3 CI build
  .github/workflows/ci.yml
  README.md
  requirements.txt
Labels: ci

#4 Switch to repotool manifest and fix whitespace
  .github/workflows/ci.yml
Labels: build-config

#5 Switch to poky/dunfell-23.0.9
  .github/workflows/ci.yml
Labels: build-config

#6 H5b/development
  README.md
  dev/bootstrap.sh
  dev/init_env.sh
Labels: documentation, enhancement

#7 Enable meta-protos in development setup
  .github/workflows/ci.yml
  README.md
  dev/bootstrap.sh
  requirements.txt
Labels: build-config

#10 Map DL_DIR and SSTATE_DIR volumes
  .gitignore
  README.md
  dev/bootstrap.sh
  dev/init_env.sh
Labels: build-config, documentation, enhancement
