Repository jhnc-oss/yocto-build, pull requests merged in 2021-09, with the labels that each got.

#16 Update step branch
  .github/workflows/ci.yml
Labels: ci

#19 Extend CI builds to x86 and x86_64
  .github/workflows/ci.yml
Labels: ci, enhancement

#21 Switch CI to actually use meta-protos
  .github/workflows/ci.yml
Labels: bug, build-config, enhancement
