Repository jhnc-oss/yocto-build, pull requests merged in 2023-10, with the labels that each got.

#60 H5b/for dunfell
  README.md
  dev/bootstrap.sh
Labels: bug

#62 Update images to Fedora 38
  .github/workflows/ci.yml
  dev/bootstrap.sh
Labels: ci, build-config, enhancement

#61 Update CI image on dunfell
  .github/workflows/ci.yml
Labels: ci, yocto: dunfell
