Repository jhnc-oss/yocto-build, pull requests merged in 2023-08, with the labels that each got.

#51 Adapt syntax to kirkstone
  .github/workflows/ci.yml
  dev/bootstrap.sh
Labels: build-config

#55 Sync main to kirkstone
  .github/workflows/sync-main.yml
Labels: ci

#54 Document supported versions
  README.md
Labels: documentation
