Repository jhnc-oss/yocto-build, pull requests merged in 2024-12, with the labels that each got.

#78 Add Scarthgap to docs
  README.md
Labels: documentation

#79 Switch main to scarthgap
  .github/workflows/sync-main.yml
  README.md
  dev/bootstrap.sh
  dev/init_env.sh
Labels: yocto: scarthgap

#82 Update TEMPLATECONF to valid path
  .github/workflows/ci.yml
Labels: build-config, yocto: scarthgap
