Repository jhnc-oss/yocto-build, pull requests merged in 2025-01, with the labels that each got.

#83 Update CI build to Fedora 40 based image
  .github/workflows/ci.yml
Labels: ci

#84 Update local build to Fedora 40 based image
  dev/bootstrap.sh
Labels: build-config

#89 Adapt MANIFEST_BRANCH to prevent TEMPLATECONF error
  .github/workflows/ci.yml
  dev/bootstrap.sh
Labels: bug, yocto: kirkstone
